---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r loading_and_processing}
unzip("activity.zip", files="activity.csv")
dta <- read.csv("activity.csv")
dta_2 <- dta[!is.na(dta$steps),] 
dta_hist <- data.frame(date=levels(dta_2$date))
for (i in dta_2$date) {
      dta_hist[match(i,dta_hist$date),2] <- sum(dta_2[dta_2$date==i,"steps"])
}
```


## What is mean total number of steps taken per day?
```{r mean_and_total}
hist(dta_hist[,2], breaks=10)

mean(dta_hist[!is.na(dta_hist[,2]),2])

median(dta_hist[!is.na(dta_hist[,2]),2])
```


## What is the average daily activity pattern?
```{r avg_daily}
aux <- data.frame(interval=simplify2array(labels(table(dta_2$interval))))

for (i in aux[,1]) {
      aux[match(i,aux[,1]),2] <- mean(dta_2$steps[dta_2$interval==i], na.rm=TRUE)
}

plot(aux[,2], type="l")

aux[match(max(aux[,2]),aux[,2]),1]
```


## Imputing missing values
```{r substitute NA for avg of interval}
dta_na <- sum(is.na(dta[,1]))
attach(dta_2)
avgRows <- ave(steps, interval)
intRows <- dta_2[,3]
detach()
dta_clean <- dta
for (i in 1:length(dta_clean[,1])) {
      if (is.na(dta_clean[i,1])) {
            dta[i,1] <- avgRows[match(dta_clean[i,3], intRows)]
      }
}

dta_hist_clean <- data.frame(date=levels(dta_clean$date))
for (i in dta_clean$date) {
      dta_hist_clean[match(i,dta_hist$date),2] <- sum(dta_clean[dta_clean$date==i,"steps"])
}
hist(dta_hist_clean[,2], breaks=10)

mean(dta_hist_clean[!is.na(dta_hist_clean[,2]),2])

median(dta_hist_clean[!is.na(dta_hist_clean[,2]),2])

```
## Are there differences in activity patterns between weekdays and weekends?
